name: ecommerce
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #A build system for Dart code generation and modular compilation
  build_runner:
  # State management
  flutter_bloc:
  # Code generator (mainly used with cubit & retrofit)
  freezed:
  freezed_annotation:
  # for dependency injection
  get_it:
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable:
  json_annotation:
  # Networking
  dio:
  retrofit:
  retrofit_generator:
  pretty_dio_logger:
  # localization
  intl:
  easy_localization:
  # for splash screen
  flutter_native_splash:
  # An SVG rendering and widget library for Flutter, which allows painting
  flutter_svg:
  # for adapting screen and font size.
  flutter_screenutil:
  # A flutter library to show images from the internet and keep them in the cache directory.
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true


